baseURL = "/"
title = "Peachy Keen Green"
locale = "en"
summaryLength = 30

contentDir = "src"
layoutDir = "page_layouts"
publishDir = "docs"

enableGitInfo = false

[frontmatter]
  lastmod = ["lastmod"]

[[module.mounts]]
source = "src"
target = "content"

[[module.mounts]]
source = "page_layouts"
target = "layouts"

[[module.mounts]]
source = "static"
target = "static"

[[module.mounts]]
source = "archetypes"
target = "archetypes"



[taxonomies]
  category = "categories"

[permalinks]
  posts = "/:slug/"

[params]
  version = "1.0.8"
  author = "Patricia Schank"
  copyrightStartYear = "2015"

[outputFormats.RECIPESJS]
  mediaType = "text/javascript"
  baseName = "recipes"
  isPlainText = true

[outputs]
  home = ["HTML", "JSON", "RECIPESJS"]


