baseURL = "/"
title = "Peachy Keen Green"
locale = "en"
summaryLength = 30

contentDir = "src"
layoutDir = "page_layouts"
publishDir = "docs"

[[module.mounts]]
source = "src"
target = "content"

[[module.mounts]]
source = "page_layouts"
target = "layouts"



[taxonomies]
  category = "categories"

[permalinks]
  posts = "/:slug/"

[params]
  version = "1.0.7"

[outputs]
  home = ["HTML", "JSON"]


